name: Deploy GitHub Pages
run-name: ${{ github.actor }} is deploying pages.

on:
  push:
    branches:
      - main

jobs:
  Deploy-Github-Pages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out source repository
        uses: actions/checkout@v4

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: List files in the source repository
        run: |
          pwd
          ls
          ls ${{ github.workspace }}

      - name: Check out target repository
        uses: actions/checkout@v4
        with:
          repository: "xiyaozhuang/action-target"

      - name: List files in the target repository
        run: |
          pwd
          ls
          ls ${{ github.workspace }}

      - run: echo "ğŸ This job's status is ${{ job.status }}."
